initro_text = "Press any button to begin"
interaction_text = "choose a direction in which you want to interact"
inspection_text = "choose a direction which you want to inspect"
rest_text = "write how much turns you want to rest or write * to rest until full regeneration: "
autor_text = "by Bobak Świstak"
